name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main   # Or any other branch you want to deploy from
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image to Docker Hub
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/medusa-task:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/medusa-task:latest

  deploy:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
